# Generated by Django 4.2.3 on 2023-08-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSuitability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255, unique=True)),
                ('suitability', models.CharField(max_length=255)),
                ('score1_p', models.FloatField()),
                ('score1_m', models.FloatField()),
                ('score2_p', models.FloatField()),
                ('score2_m', models.FloatField()),
                ('score3_p', models.FloatField()),
                ('score3_m', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('Age', models.IntegerField()),
                ('I', models.FloatField()),
                ('S', models.FloatField()),
                ('N', models.FloatField()),
                ('concern', models.CharField(max_length=255)),
                ('anger', models.CharField(max_length=255)),
                ('atrophy', models.CharField(max_length=255)),
                ('inferiority', models.CharField(max_length=255)),
                ('impulse', models.CharField(max_length=255)),
                ('faint', models.CharField(max_length=255)),
                ('E', models.FloatField()),
                ('warmth', models.CharField(max_length=255)),
                ('sociability', models.CharField(max_length=255)),
                ('assertiveness', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('excitement', models.CharField(max_length=255)),
                ('optimism', models.CharField(max_length=255)),
                ('O', models.FloatField()),
                ('imagination', models.CharField(max_length=255)),
                ('aesthetic', models.CharField(max_length=255)),
                ('feelings', models.CharField(max_length=255)),
                ('adventurous', models.CharField(max_length=255)),
                ('originality', models.CharField(max_length=255)),
                ('values', models.CharField(max_length=255)),
                ('A', models.FloatField()),
                ('trust', models.CharField(max_length=255)),
                ('honesty', models.CharField(max_length=255)),
                ('altruism', models.CharField(max_length=255)),
                ('compliance', models.CharField(max_length=255)),
                ('modesty', models.CharField(max_length=255)),
                ('gentleness', models.CharField(max_length=255)),
                ('C', models.FloatField()),
                ('confidence', models.CharField(max_length=255)),
                ('order', models.CharField(max_length=255)),
                ('calling', models.CharField(max_length=255)),
                ('achievement', models.CharField(max_length=255)),
                ('autonomy', models.CharField(max_length=255)),
                ('deliberation', models.CharField(max_length=255)),
                ('job_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='edit.jobsuitability')),
            ],
        ),
    ]
