# Generated by Django 4.2.3 on 2023-08-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_remove_jobsuitability_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='suitability_score',
            field=models.FloatField(default=0),
        ),
    ]
