# Generated by Django 4.2.3 on 2023-08-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_job_suitability_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='suitability_score',
        ),
    ]
